### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by brberis** [brberis/ai-dream-io#2]
1- As a user I want to buy images for my business.

2- When I enter to Ai Dream I find description of the service and different sections depends what I’m looking for.

- Logo Design Concepts 
- Product Design Concepts
- Images for Marketing
- Social Media Marketing 

3- I enter to Logo Design Concepts and I see some static examples that I can generate. And a button that says Start generating now!

4- I press the button and a see a form to fill information about my design. But the submit button says “Just $0.5 per image (Buy credits)”.

5- I press the button and I see a user registration modal form.

6- I fill all my personal info and press save.

7- My profile page appears with 5 free credit (optional) and a button to buy more credits.

8- When I press the buy credit button I see a checkout credit modal that have pre credits amount $5 $10 $50. 

9- I select the $5 credit button and the Stripe modal opens. 

10- I enter my credit card info and checkout.

11- The Stripe page redirect to the same logo generation (if we can store that url in state context memory).

12- Now I see the logo form and a submit button that says Submit or Generate Now.

13- I press the button and I see 3 images generated. Each image has a icon to download and other icon to save it to my collections.

**Comment by devihall** [comment]
Homepage>Signup>Add credits page> Search form page> Results page (which will have  option on each image to save to collection")>view collection page

if already Signed up but no credits>Add credits page> Search form page> Results page (which will have  option on each image to save to collection")>view collection page

If already Signed up and has credits >Search form page> Results page (which will have  option on each image to save to collection")>view collection page
